---
# driver:
#   name: docker
#   use_sudo: false
driver:
  name: vagrant
  boot_timeout: 300
  customize:
    memory: 1024
  # network:
  #   - ["private_network", {ip: "10.0.0.10"}]

transport:
  port: 2222

provisioner:
  name: ansible_playbook
  hosts: localhost
  requirements_path: requirements.yml
  require_ansible_repo: true
  ansible_verbose: false
  ansible_version: latest
  require_chef_for_busser: false

platforms:
  - name: centos-7.3

verifier:
  name: serverspec
  sudo_path: true
  ruby_bindir: '/usr/bin'

suites:
  - name: default
    driver:
    network:
      - ["private_network", {ip: "10.0.0.10"}]
    verifier:
      default_pattern: true
